### ISSUE TITLE
KYC-chain for Android

### ISSUE THREAD

**Issue by whiteyhat** [rudrakh97/KYC-chain#1]
Hey!

I was wondering if this repository has any APIs or can be integrated for a KYC process in Java (**Android**)!

**Comment by rudrakhp** [comment]
This repo uses the Web3-js ( https://github.com/ethereum/web3.js/ ) which is an API in JavaScript. You may have to use Web3-j ( https://github.com/web3j/web3j ) for using the interface in Java. So I am afraid it cannot be integrated directly into Android applications in it's present form. Although  you can try using third party services like Infura or Etherscan that allow interacting the blockchain through their servers, hence call directly to their APIs.

**Comment by whiteyhat** [comment]
Interesting!

I will read the documentation right now.

This repository includes an OCR algorithm to provide a KYC verification such as [OnFido](https://onfido.com) or [Jumio](https://www.jumio.com)?

Thanks:smiley:

**Comment by rudrakhp** [comment]
No, we have not included advanced verification mechanisms as of now since this is a prototype, although we plan to do so in the near future. 😄

**Comment by whiteyhat** [comment]
Nice. I'd like to fork it in a short term future or collaborate.

So this KYC stores identity on the **Ethereum Blockchain** or how does it work?:smiley:

**Comment by rudrakhp** [comment]
You are welcome 😃 
Yes, the identities are stored on the blockchain, but not directly as it is not practical in terms of memory size. We store hashes instead.
