### ISSUE TITLE
Unable to execute. It seems compiler.js file is missing

### ISSUE THREAD

**Issue by pcakhilnadh** [rudrakh97/KYC-chain#10]
#bug 
I have followed all the steps and when I tries to execute, Im getting following error

> (function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath"normalize";var ret=nodeFS["readFileSy
> 
> TypeError: Cannot read property 'interface' of undefined at Timeout.afterDelay [as _onTimeout] (/Users/pc/Documents/Programs/KYC-chain-master/root/init.js:16:59) at ontimeout (timers.js:458:11) at tryOnTimeout (timers.js:296:5) at Timer.listOnTimeout (timers.js:259:5)` 
> 

 I've asked this question in stackoverflow too. https://stackoverflow.com/questions/55999969/typeerror-cannot-read-property-interface-of-undefined

What I'm concluding is that compiler.js file is missing from the project. 

System specifications Im using 
OS macOs
node version 9.4.0
solidity 0.4.4
web3  0.19
npm 5.6.0

**Comment by rudrakhp** [comment]
Hey pc,
I have updated the requirements page. You need to upgrade the solidity package 0.4.26.
Good luck!
